[project]
name = "libreturner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "mediapipe>=0.10.21",
    "pdf2image>=1.17.0",
    "pypdf>=6.0.0",
    "python-slugify>=8.0.4",
]
